stages:

  data_ingestion:
    cmd: python src/risk_predictor/pipeline/stage_01_dataingestion.py
    deps:
      - src/risk_predictor/pipeline/stage_01_dataingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/data.csv:
          persist: true
          cache: true


  data_preprocessing:
    cmd: python src/risk_predictor/pipeline/stage_02_data_preprocessing.py
    deps:
      - src/risk_predictor/pipeline/stage_02_data_preprocessing.py
      - config/config.yaml
      - artifacts/data_ingestion/data.csv
    outs:
      - artifacts/data_preprocessing/pickle/X_train.joblib:
          persist: true
          cache: false
      - artifacts/data_preprocessing/pickle/X_test.joblib:
          persist: true
          cache: false
      - artifacts/data_preprocessing/pickle/y_train.joblib:
          persist: true
          cache: false
      - artifacts/data_preprocessing/pickle/y_test.joblib:
          persist: true
          cache: false


  model_trainer:
    cmd: python src/risk_predictor/pipeline/stage_03_model_trainer.py
    deps:
      - src/risk_predictor/pipeline/stage_03_model_trainer.py
      - config/config.yaml
      - params.yaml
      - artifacts/data_preprocessing/pickle/X_train.joblib
      - artifacts/data_preprocessing/pickle/y_train.joblib

    outs:
      - artifacts/model_trainer/best_model.joblib:
          persist: true
          cache: false
      - artifacts/model_trainer/reports:
          persist: true
          cache: false
      - artifacts/model_trainer/plots:
          persist: true
          cache: false


  model_evaluation:
    cmd: python src/risk_predictor/pipeline/stage_04_model_evaluation.py
    deps:
      - src/risk_predictor/pipeline/stage_04_model_evaluation.py
      - config/config.yaml
      - params.yaml
      - artifacts/data_preprocessing/pickle/X_test.joblib
      - artifacts/data_preprocessing/pickle/y_test.joblib
      - artifacts/model_trainer/best_model.joblib
    outs:
      - artifacts/model_evaluation/metrics.json:
          persist: true
          cache: false
      - artifacts/model_evaluation/plots:
          persist: true
          cache: false