  RandomForestClassifier:
    n_estimators: 200
    max_depth: 10
    class_weight: balanced
    random_state: 42

  XGBoost:
    n_estimators: 300
    max_depth: 8
    learning_rate: 0.05

  KNN:
    n_neighbors: 5

  LogisticRegression:
    C: 1.0
    max_iter: 1000

  DecisionTree:
    max_depth: 10
    min_samples_split: 5




